### ISSUE TITLE
Lucas Bohórquez - Organizar nombres/ubicaciones de documentos y carpetas

### ISSUE THREAD

**Issue by Sebas-Orozco** [lucasucaldas/Proyecto_Software_II_BlastCode_2021_01#142]
TENER EN CUENTA ESTÁNDARES:
En la carpeta "Gestión del proyecto" estarán por el momento:
* Carpetas:
  + Documentación general
  + Primera iteración
* Documentos:
  Formatos de muestra (Generalmente dados por el profesor "vacíos") para la creación de los informes:
  + Formato de planeación (vacío)
  + Formato de documento de lanzamiento (vacío)
  + Formato de requisitos (vacío)
  + Formato Consolidados inspección (vacío)

En la carpeta "Documentación general" estará todo los documentos relacionados con información global de todo el proyecto:
* Documentos:
  + Reglas de juego.pdf
  + Roles de bolsillo.pdf
  + Documento de planteamiento del proyecto.pdf
  + Diseño_restaurante_saboreo.uml
  + Diagrama_contexto.draw.io

- [x] Asegurar información que se encuentra en el drive hasta el momento, para no perderla con los cambios que se van a agregar a la estructura.
- [x] Documento de reglas de juego: organizar nombre, mover a "Documentación general"
- [x] Documento de roles de bolsillo: organizar nombre, mover a "Documentación general"
- [x] Documento selección de modulo: sacar de carpeta de proyecto y ubicarlo en talleres de blastcode
- [x] Documento diagrama de contexto: Renombrar de acuerdo a los estándares de calidad, y ubicar en "Documentación general"
- [x] Eliminar la carpeta de "diagramas iniciales" con el contenido restante
- [x] En carpeta "Primera iteración", el formato de planeación cambiar nombre a "Planeación_primera_iteración.xlsx" 
- [x] En carpetas de "Primera iteración/Inspección de casos de uso" y "Primera iteración/Inspección de casos de uso" cambiar nombres de carpetas actuales de casos de uso de acuerdo al estándar, es decir, "código_nombre del caso de uso en UpperCamelCase". todo lo que tenga que ver con caso de uso es con esta estructura
- [x] Documento formato de inspección consolidado: cambiar nombre a "Formato consolidados de inspección" y reubicar en carpeta de "Gestión del proyecto"
- [x] Los formatos lista de chequeo de casos de uso, modelo de análisis y formato de revisión buscarlos en la carpeta del profesor (el archivo vacío) y organizarle el nombre y ubicarlo en carpeta de "Gestión del proyecto"
- [x] En carpeta "Primera iteración/Mockups", organizar nombre de documento de mockups a "Mockups.draw.io" y reubircar a documentación general

**Comment by Sebas-Orozco** [comment]
- [ ] ¿2 carpetas de recolección y validación de requisitos?¿una está mala?

**Comment by lucasucaldas** [comment]
No le entiendo Sebas, me envía una imagen por fa
