### ISSUE TITLE
SFCU07 - Lucas Bohórquez - Organizar diagramas y mockups

### ISSUE THREAD

**Issue by Sebas-Orozco** [lucasucaldas/Proyecto_Software_II_BlastCode_2021_01#164]
Se deben organizar nombres, ubicaciones, formatos, de diagramas y mockups para cumplir con el estándar:
- [x] Ubicar diagrama de clases corregido en el documento DiseñoRestauranteSaboreo.uml,
- [x] Exportar diagrama de clases en formato jpg con el nombre correcto y guardarlo en la carpeta de diagramas de clase de la primera iteración
- [x] Ubicar diagrama de secuencia corregido en el documento DiseñoRestauranteSaboreo.uml,
- [x] Exportar diagrama de secuencia en formato jpg con el nombre correcto y guardarlo en la carpeta de diagramas de secuencia de la primera iteración

- [x] Ubicar mockup en el documento DiagramaContexto.draw.io, y si ya está ubicado solo organizar nombre del respectivo mockup
- [x] Exportar mockup en formato jpg con el nombre correcto y guardarlo en la carpeta de mockups de la primera iteración

**Comment by lucasucaldas** [comment]
60 minutos

**Comment by Sebas-Orozco** [comment]
- [ ] ¿nombres pestañas de draw.io por nombres de casos de uso?

**Comment by lucasucaldas** [comment]
Si Sebas
